name: cine_flow
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  get: ^4.7.3
  cached_network_image: ^3.4.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  fpdart: ^1.2.0
  flutter_dotenv: ^6.0.0
  shimmer: ^3.0.0
  google_fonts: ^7.0.0
  flutter_screenutil: ^5.9.3
  carousel_slider: ^5.1.1
  intl: ^0.20.2
  change_app_package_name: ^1.5.0
  flutter_animate: ^4.5.2
  flutter_native_splash: ^2.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.8
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/

 
flutter_native_splash:
  color: "#0F1014"
  # image: ""
  fullscreen: true
  android_12:
    color: "#0F1014"
    icon_background_color: "#0F1014"